# Jarvis 2.0 - Railway Deployment Configuration
[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/status"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment Variables
[env]
FLASK_ENV = "production"
FLASK_APP = "web_app.py"
PYTHONUNBUFFERED = "1"
PORT = "5000"

# Database Configuration (Railway PostgreSQL)
DATABASE_URL = { fromSecret = "DATABASE_URL" }
REDIS_URL = { fromSecret = "REDIS_URL" }

# AI & Security
GOOGLE_API_KEY = { fromSecret = "GOOGLE_API_KEY" }
JWT_SECRET_KEY = { fromSecret = "JWT_SECRET_KEY" }

# Blockchain Configuration
BLOCKCHAIN_DIFFICULTY = "4"
MEMORY_VALIDATION_ENABLED = "true"

# Quantum Processing
QUANTUM_SIMULATION_ENABLED = "true"
MAX_QUBITS = "8"

# Logging & Monitoring
LOG_LEVEL = "INFO"
SENTRY_DSN = { fromSecret = "SENTRY_DSN" }

# File Storage
UPLOAD_FOLDER = "/app/data/uploads"
MAX_CONTENT_LENGTH = "16777216"  # 16MB

# CORS Configuration
CORS_ORIGINS = "*"

# WebSocket Configuration
SOCKETIO_CORS_ALLOWED_ORIGINS = "*"

# Rate Limiting
RATELIMIT_DEFAULT = "100 per minute"
RATELIMIT_STORAGE_URL = { fromSecret = "REDIS_URL" }
